services: 
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: learn-php
    restart: always
    working_dir: /var/www/
    volumes:
      - ../src:/var/www
  nginx:
    image: nginx:1.27.2-alpine
    container_name: learn-php-nginx
    restart: always
    ports:
      - 8000:80
    volumes:
      - ../src:/var/www
      - ./nginx:/etc/nginx/conf.d
